### ISSUE TITLE
Is pretty-printing JS in-scope?

### ISSUE THREAD

**Issue by Adjective-Object** [tdewolff/parse#108]
Hello!

I've been writing a JS pretty-printer for parse/js at work, and was wondering if there's any interest in upstreaming it.

I'm happy to push my changes into their own repo, but I'd like to contribute back to this project if you're interested in having the work.

**Comment by Adjective-Object** [comment]
While fuzzing, I've also run into a few cases where parsing then calling .JS() on the parsed AST will result in either:
- an AST that parses to a different AST than the original
- a panic

**Comment by tdewolff** [comment]
Hey Max, thanks for the effort! Yes, pretty print could be incorporated in
this repo, I would be happy to help!

With respect to the panic, do you have a minimal example to reproduce? In
general the AST should be the same after repeated parsing, but there may be
minor differences, in any case, can you post the inputs that result in
different AST upon successive parsing? Thanks!

**Comment by Adjective-Object** [comment]
Pushed a change that adds fuzzing and fixes for the various stability issues & crashes I ran into in #109. It's quite a lot of small tweaks around the .JS() and parse() steps.

I'm counting this as a prerequisite to pretty-printing, since the pretty-printing logic is _also_ tested by fuzzing that input strings re-parse to a stable representation with their inputs.

**Comment by tdewolff** [comment]
I've completely refactored the code to generate JS and JSON, you can now use `ast.JSString() string` or `ast.JSONString() (string, error)` to get a pretty-print JS/JSON string of the AST. Otherwise, you can use the `JS(io.Writer)` or `JSON(io.Writer) error` functions on all nodes.

Fuzzing is added for pretty-printing in `tests/js-string`, and bug fixes will come raining. Considering this issue fixed, if you have further problems please re-open! Thanks for all the work!

**Comment by tdewolff** [comment]
I've run the fuzzing for a few hours and it seems it has caught the majority of bugs. This was a very helpful way to discover new bugs, thanks a lot! I will keep the fuzzer running a little longer, and of course OSSFuzz will run periodically.
