### ISSUE TITLE
Set new class in HTML source

### ISSUE THREAD

**Issue by jimafisk** [tdewolff/parse#121]
My apologies if I'm trying to do something the project isn't meant for!

**Question:** When parsing HTML is it possible to update the underlying markup, like adding new classes to elements?

**Context:** I'm trying build a template engine that scopes CSS to elements in a component so I'd be adding hashed classes like `class="myproj-K7ryxB"` throughout the dom.

**Example:** I've been following along the excellent example from the docs (https://github.com/tdewolff/parse/tree/master/html#examples), below is a slightly modified version with a comment:

```go
package main

import (
	"os"

	"github.com/tdewolff/parse/v2/html"
)

func main() {
        markup := `
<!DOCTYPE html>
<html lang="en">
   <head>
     <title>Test</title> 
   </head>
   <body>
      <h1>Test</h1>
   </body>
</html>
`

	l := html.NewLexer(parse.NewInputString(markup))
	for {
		tt, data := l.Next()
		switch tt {
		case html.ErrorToken:
			if l.Err() != io.EOF {
				fmt.Println("Error on line", l.Line(), ":", l.Err()) // Sidenote: l.Line() doesn't seem to exist for me
			}
			return
		case html.StartTagToken:
                        tag := strings.TrimPrefix(string(data), "<")
			fmt.Println("Tag", tag)
			for {
				ttAttr, dataAttr := l.Next()
				if ttAttr != html.AttributeToken {
					break
				}
                                fmt.Println("Attribute", string(dataAttr))

				key := string(l.AttrKey())
                                val := strings.Trim(string(l.AttrVal()), `"`)
                                if key == "class" {
                                        classes := strings.Split(val, " ")
                                        // Is there a way to modify the initial `markup` string to add a new class here?
                               }		
			}
		// ...
		}
	}
}
```

I was mainly curious if this is possible and whether I'm way off-base with my approach here? I very much appreciate any references you can point me to! Thank you!

**Comment by tdewolff** [comment]
Hi Jim, the parser was primary built to be used by the minifiers. They are high-performance parsers and will read through a file/buffer efficiently. What is not supported is in-place modification, since this would be highly inefficient; each insertion would need to expand the buffer, move all following bytes further down, and copy the new bytes in place.

You can achieve what you want by writing out the new HTML file, adding the new CSS class when appropriate. Unfortunately, there is no AST tree generation which would allow you to change some values and then write out the (perhaps minified) HTML file using this library.
