### ISSUE TITLE
Ability to get position in parsers

### ISSUE THREAD

**Issue by YafimK** [tdewolff/parse#49]
Hi,
Is there anyway to get the current position of the Json parser (and xml as well) when it returns an item?

I thought on creating ability to get  the buffer lexer (since it has the "offset" method) or simply giving it as method on the parser? Like simple additional constructor that gets the buffer.lexer so that it's properties get exposed.

after an additional check - it seems that the way would be to either change the lexer to store the last position on shift and skip, or changing the parser itself to return the position whenever it returns the value.

thanks ahead.

**Comment by tdewolff** [comment]
We could expose the `buffer.Lexer` that is within each parser so that the `Offset() int` function can be called to obtain the offset in the buffer. That way any package outside of `parse` could also create a new `Error` or `Position` structure.

**Comment by YafimK** [comment]
Great!
But it doesn't seem to resolve the issue entirely in the case of Json parser. The json parser uses "shift", which makes the position given by the lexer irreverent but the last "z.start" useful.
So I'd suggest to also add "previous position" property that holds the last "z.start" before it's changed (for example due to "shift").

**Comment by YafimK** [comment]
Are there any contribution guidelines if i make this change and PR?

**Comment by tdewolff** [comment]
There are no official contribution guidelines really, since nobody has contributed much haha. In any case, it would be preferable if changes were small and don't change too much of the structure of the code. I'm hesitant with bigger changes as the complexity often results in subtle breakages. However, contributions are appreciated, as well as code comments and ideas and discussions for improvement!

I've had a similar problem lately with the CSS parser in `css/parse.go`, it didn't really make sense to use the `z.pos` offset, but rather the `z.start` offset as it had already been shifted. Not sure how to proceed, expose two functions with different names?

**Comment by tdewolff** [comment]
I've added the `Offset() int` functions to all lexers and parsers which will return the position the lexer/parser is at. In your use case, you would call this before `Next()` to obtain the beginning offset of the token returned by that `Next()`.
