### ISSUE TITLE
v2.5.0 breaks signature of css.NewParser

### ISSUE THREAD

**Issue by bradleypeabody** [tdewolff/parse#64]
It looks like in v2.4.4 css.NewParser was:

`func NewParser(r io.Reader, isInline bool) *Parser {`

But now in 2.5.0 is:

`func NewParser(r *parse.Input, isInline bool) *Parser {`

I have a bunch of existing code that depends on being able to pass an io.Reader for parsing. (And this change breaks semantic versioning rules.)

A couple alternative approaches:
- Another method like NewInputParser() could accept a *parse.Input, leaving NewParser as it was before
- Or NewParser() could retain the old signature and then inside the method do a type assertion to check if *parse.Input was provided and perform additional logic in that case.

Any thoughts or suggestions on this?

**Comment by tdewolff** [comment]
Thanks for the report, you're right this should've triggered a new major release. However the fix is pretty easy, instead of calling `css.NewParser(r, false)` you should call

```go
input := parse.NewInput(r)
p := css.NewParser(input, false)
// ...
input.Restore()
```

or if the byte-slice behind `r` is not used anywhere else (which is generally the case), then just call

```go
p := css.NewParser(parse.NewInput(r), false)
```

The original parsers all had the `Restore` function implemented themselves, so if you didn't call it then than don't call it now either.

**Comment by bradleypeabody** [comment]
Okay, understood and thanks.  Yes, this seems like a simple change and I'll go ahead and update my code the plan is to keep it like this moving forward.

**Comment by bradleypeabody** [comment]
I got everything converted no problem.  In any case, thanks for this library! - It's by far the most capable Go CSS parser I've seen and I've used it a few times with excellent results.  Most recently here: https://github.com/gotailwindcss/tailwind

**Comment by tdewolff** [comment]
Thank you for the kind words, I'm happy to hear it works well for you!
