### ISSUE TITLE
JS: return byte slices for JSON methods

### ISSUE THREAD

**Issue by 89z** [tdewolff/parse#85]
Currently the JSON methods return a string, example:

https://github.com/tdewolff/parse/blob/92ee1b3342221fc0d72623f8c224c2947d162cd8/js/ast.go#L1580-L1591

However looking at the implementation, it looks like the data is originally in bytes slices, and is cast to string. This is fine, but probably a common use case would be to take the JSON string and Unmarshal it. So currently this package is casting to string, then the user would cast back to bytes to Unmarshal.

Would you consider just returning byte slices for the JSON methods?

**Comment by tdewolff** [comment]
In general all the parse package uses byte slices, especially when referring to the source code. In this case (as for the `JS` functions as well) we are rebuilding a new representation that is only partially referring to the source code. The idea was to reflect the `String` method and provide a "view" of the AST in different forms (an arbitrary string representation, a JavaScript representation, and a JSON representation if possible). I agree the usefulness of returning a byte-slice, but that would imply changing the `JS` methods as well. This may be a good idea but I can't fully overview the different usages of `JS` and `JSON` and can't make a well-founded decision at the moment. For now it seems trivial to cast the string to a byte-slice, incurring a performance penalty, until there is a consensus..

**Comment by 89z** [comment]
Regarding JavaScript, I think a string is better, as people might use the output here with something like this:

https://godocs.io/strconv

While with JSON, people might use the output here with something like this:

https://godocs.io/encoding/json

`strconv` expects `string` input, while `encoding/json` expects `[]byte` input. So ideally `JS` methods would return `string`, and `JSON` methods would return `[]byte`. If you want to keep functions as is I respect that, but I figured since the `JSON` methods are new, I would make a suggestion that would improve user experience, as well as performance. Thanks for the response.

**Comment by tdewolff** [comment]
I don't really follow why people would use `strconv` for the output of `JS()`, I would guess the output is either used to write to a file, print to console/dialog, saved in a DB or sent by HTTP / other protocol. The same I would guess for `JSON()`, but I confess I don't fully oversee the potential applications. In any case, I think you have a good point for `JSON()` which should return `[]byte`, but I suspect that `JS()` may benefit from the same and be consistent with JSON. What's your opinion?

**Comment by 89z** [comment]
As a workaround, I wrote my own JSON scanner:

https://github.com/89z/parse/blob/master/json/json.go

basically it scans through a byte slice, until it finds a JSON token. Then it keeps scanning until end of slice or error. If the subslice is valid JSON, then its returned. Repeat process, returning all valid JSON subslices. I still think it would be useful to return byte slices with the `tdewolff/parse` JSON methods, but I wanted to update on my progress.

**Comment by tdewolff** [comment]
Thanks for the update. I still intend to work on this issue when I get to it. In general, writing a custom scanner is likely to be much much faster, though be careful with edge cases ;-)

**Comment by 89z** [comment]
Hey I also wanted to mention to you, wouldnt it be easier for `tdewolff/parse` to have something like this:

~~~go
type JSONer interface {
   JSON() (string, error)
}
~~~

then you dont have to add empty JSON methods to all those types that dont need it. Then at the call site, you could do type assertion:

~~~go
j, ok := something.(JSONer)
if ok {
   s, err := j.JSON()
   // blah blah
}
~~~

**Comment by tdewolff** [comment]
Good suggestion. Some additional thinking about returning `[]byte`, it is actually pretty inefficient to return new slices for every function instead of appending to a given slice (expanding capacity as needed) or writing to a bytes writer (same thing really). So I was thinking something along the lines of `JSON(buf *bytes.Buffer) error` or `JSON(buf []byte) error)`. This will greatly reduce the number of allocations needed, especially if the user pre-allocates or already has space at the destination (so that we can write directly!). What do you think?

**Comment by 89z** [comment]
Ergonomically, its definitely a loss against just returning a byte slice. However if its a significant performance increase, then its probably worth doing. I would think that something like this would have similar result:

~~~go
func (something) JSON() ([]byte, error) {
   var b bytes.Buffer
   b.WriteString("hello")
   b.WriteString(" world")
   return b.Bytes(), nil
}
~~~

but if my code above is still poor performance, then I think this would be better:

~~~
JSON(buf *bytes.Buffer) error
~~~

as it matches something like `json.Compact` [1], and it would be easier for end user:

~~~go
buf := new(bytes.Buffer)
err := something.JSON(buf)
~~~

1. https://godocs.io/encoding/json#Compact

**Comment by tdewolff** [comment]
The example you wrote has the same problem, where recurring calls to JSON methods will allocate new `bytes.Buffer`. I've implemented that just now, please let me know how it goes!

**Comment by 89z** [comment]
Hm, im getting weird results. First I tried this:

~~~go
package main

import (
   "bytes"
   "fmt"
   "github.com/tdewolff/parse/v2"
   "github.com/tdewolff/parse/v2/js"
   "os"
)

type visit struct {
   bytes.Buffer
   nodes [][]byte
}

func (visit) Exit(js.INode) {}

func (v *visit) Enter(n js.INode) js.IVisitor {
   j, ok := n.(js.JSONer)
   if ok {
      err := j.JSON(&v.Buffer)
      if err == nil {
         v.nodes = append(v.nodes, v.Bytes())
      }
      return nil
   }
   return v
}

func main() {
   f, err := os.Open("ig.js")
   if err != nil {
      panic(err)
   }
   defer f.Close()
   ast, err := js.Parse(parse.NewInput(f))
   if err != nil {
      panic(err)
   }
   var vis visit
   js.Walk(&vis, ast)
   for k, v := range vis.nodes {
      fmt.Printf("%v %s\n\n", k, v)
   }
}
~~~

but the Buffer is retaining the previous bytes, so each subsequent element is prefixed by the previous bytes. Then I tried adding a `v.Reset()` before the JSON call, but I still get a malformed result. I guess I could do a `bytes.NewBuffer` inside the `Enter` method, but isnt that throwing away the work you did to avoid extra allocations?

**Comment by 89z** [comment]
This seems to fix it:

~~~go
func (v *visit) Enter(n js.INode) js.IVisitor {
   j, ok := n.(js.JSONer)
   if ok {
      v.Reset()
      err := j.JSON(v.Buffer)
      if err == nil {
         node := make([]byte, v.Len())
         copy(node, v.Bytes())
         v.nodes = append(v.nodes, node)
      }
      return nil
   }
   return v
}
~~~

but that definitely feels icky. But I guess if its more performant, it might be worth the tradeoff.

**Comment by tdewolff** [comment]
Yes, the `JSON` methods now _allow_ you to be more performant, but you may still choose not to do so obviously! In your case you want a new byte-slice for every node, so I recommend you to just allocate a new `bytes.Buffer` every time (it's the same performance-wise as you were doing, pretty much):

```go
type visit struct {
   nodes [][]byte
}

func (v *visit) Enter(n js.INode) js.IVisitor {
   j, ok := n.(js.JSONer)
   if ok {
      buf := &bytes.Buffer{}
      err := j.JSON(buf)
      if err == nil {
         v.nodes = append(v.nodes, buf.Bytes())
      }
      return nil
   }
   return v
}
```

You could of course use a single `bytes.Buffer` and append all nodes. But selecting slices from that buffer is ill-advised, because while appending other nodes, the buffer may need to expand which involves: allocate bigger slice, copy current slice to new slice, remove old slice. Or, all references to the old buffer are now invalid. The copying of the current slice upon expanding may become pretty expensive. In your case the best solution is probably what I wrote above.

The `bytes.Buffer` helps in two cases: if you need to visit and process nodes one-by-one, in which case you can reuse the buffer using `buf.Reset()`. The other case is when you need to have the entire JSON result in memory, in which case the buffer prepares that for you (instead of allocating small slices which you have to concatenate yourself, incurring other allocations). In fact, now that I think of it, it might be better even to change `bytes.Buffer` for `io.Writer` in the function signature, so that you can write to buffers, files, or network, etc.

**Comment by 89z** [comment]
Thanks for all the details and advice! I think I have a working solution now! Much appreciated. If I can help you in some way in the future, let me know.
