### ISSUE TITLE
Top-level await

### ISSUE THREAD

**Issue by blixt** [tdewolff/parse#87]
Top-level await doesn't seem to parse. This code:

```javascript
const response = await fetch("https://google.com");
```

Fails with this error:

```
unexpected fetch in const declaration on line 1 and column 24
    1: const response = await fetch("https://google.com");
```

Playground: https://play.golang.org/p/vBfz3yFM3J9

**Comment by tdewolff** [comment]
Yes, because that is actually invalid JS, see https://eslint.org/demo#eyJ0ZXh0IjoiY29uc3QgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaChcImh0dHBzOi8vZ29vZ2xlLmNvbVwiKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEyLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1lbHNlLWlmIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbXBvcnQtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNldHRlci1yZXR1cm4iOjIsIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtY2F0Y2giOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJuby13aXRoIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6eyJlczIwMjEiOmZhbHNlfX19

It returns `Parsing error: Unexpected token fetch` or `Parsing error: Cannot use keyword 'await' outside an async function` when parsing as a module.

**Comment by blixt** [comment]
It might be invalid according to ESLint's configuration, but it's definitely valid. Run this in Chrome's console and you'll see it chugging along just fine:

```javascript
const js = `const response = await fetch("https://api.coindesk.com/v1/bpi/currentprice.json"); const data = await response.json(); console.log(data);`
const url = await URL.createObjectURL(new Blob([js], { type: "text/javascript" }))
const module = await import(url)
```

<img width="1174" alt="Screen Shot 2021-09-26 at 21 00 58" src="https://user-images.githubusercontent.com/158591/134820756-f76b71a7-629e-4512-9a00-f52298107eba.png">

**Comment by blixt** [comment]
Ah I see, there's a closed issue in ESLint from when top-level `await` was a stage 3 proposal but it's stage 4 now and should be supported by parsers, even if not every browser might have it yet: https://github.com/tc39/proposal-top-level-await#ecmascript-proposal-top-level-await

**Comment by blixt** [comment]
Okay dug into it some more, ESLint 8 has support for it, but it's not fully released yet (a release candidate was made two days ago).

**Comment by 89z** [comment]
I dont think this needs to be supported. At least currently, Node doesnt support this syntax:

~~~
const response = await fetch("https://google.com");
                 ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of
modules
~~~

or in module:

~~~
const response = await fetch("https://google.com");
                 ^

ReferenceError: fetch is not defined
~~~

**Comment by 89z** [comment]
Also, "Run this in Chrome's console" in general is a terrible test, as Chrome is notorious for essentially writing their own standards.

**Comment by blixt** [comment]
But [multiple browsers](https://caniuse.com/mdn-javascript_operators_await_top_level) and [the V8 engine](https://v8.dev/features/top-level-await) that Node.js runs on under the hood support it so that alone seems to be a good reason to support it? At least I'm using this library for real production cases where top-level await might appear in the code. 

> Also, "Run this in Chrome's console" in general is a terrible test, as Chrome is notorious for essentially writing their own standards.

Maybe, though I don't think that's a discussion for this issue. Top-level await is an official TC39 ECMAScript proposal that has been fully finished (no longer a proposal but a standard) which means it's not Chrome making up their own standard. Also Safari 15 and Firefox support this.

**Comment by blixt** [comment]
Ah, turns out Node.js 14 supports this, so I don't even think the original argument for why it's not needed is valid.

**Comment by tdewolff** [comment]
I think we should support any proposal that is (close to) being integrated into the spec. This package should not be a blocker for upcoming features when used in production. The relevant implementation is fairly simple, see https://tc39.es/proposal-top-level-await/#sec-modules, and I'll try to get to it soon.

**Comment by 89z** [comment]
> At least I'm using this library for real production cases where top-level await might appear in the code.

If you have production code using unstandardized JavaScript features, then perhaps you should review the circumstances that allowed that to happen.

> Ah, turns out Node.js 14 supports this, so I don't even think the original argument for why it's not needed is valid.

Nope:

~~~
PS C:\> node --version
v16.10.0
~~~

**Comment by blixt** [comment]
@89z sorry but this is a standardized feature. All major browsers support it. So does Node.js since v14. Check your original comment and you'll see the error is not about `await` but about `fetch`. Sorry, but your comments have not been very productive to this issue since the points you're making are not correct, they're verifiably incorrect.

Try this in Node.js instead:

```javascript
const myPromise = new Promise(resolve => setTimeout(() => resolve("hello"), 1000))
export default await myPromise
```

**Comment by 89z** [comment]
> @89z sorry but this is a standardized feature. All major browsers support it. So does Node.js since v14.

Just because you say its a standardized feature, doesnt make it standardized feature. Look, I can say "the sky is green", but thats not actually true. The link provided by @tdewolff [1], appears to say "proposal", which would directly contradict the point youre trying to make.

> Check your original comment and you'll see the error is not about `await` but about `fetch`.

Your original code is:

~~~js
const response = await fetch("https://google.com");
~~~

so if you didnt want people using it, then maybe you shouldnt have posted it.

> Sorry, but your comments have not been very productive to this issue since the points you're making are not correct, they're verifiably incorrect.

Same to you.

1. https://tc39.es/proposal-top-level-await

**Comment by blixt** [comment]
> Just because you say its a standardized feature, doesnt make it standardized feature. Look, I can say "the sky is green", but thats not actually true. The link provided by @tdewolff [1], appears to say "proposal", which would directly contradict the point youre trying to make.

I'm not just saying it's a standardized proposal. That link is outdated. I already linked to the more up-to-date source for the same TC39 team saying it's Stage 4, finished, a standard. I also invite you to read the most up-to-date source for the ECMAScript standard – https://tc39.es/ecma262/ – which references top-level `await` as well. In the introduction it also links which standards it includes: https://github.com/tc39/proposals/blob/HEAD/finished-proposals.md and there you will also find top-level `await`.

I am only responding to you in the hopes that it inspires less reactionary comments based on hunches, and that you research your statements in the hopes that we can all agree much sooner on what is the actual state of things.

> so if you didnt want people using it, then maybe you shouldnt have posted it.

I explicitly stated to run it in a browser console. I said "Chrome" though "Firefox" or "Safari 15" are valid substitutes. I am sure as a Node.js developer choosing to run browser code in Node.js you are aware of the API differences and in choosing to do so (even if I never asked anyone to run this in Node.js), you would be able to substitute the code for a suitable asynchronous API in Node.js. So I don't understand why you're telling me not to post it.

> Same to you.

See the top of this comment with the correct information. I can only repeat once more what I said before.

**Comment by 89z** [comment]
> I'm not just saying it's a standardized proposal. That link is outdated. I already linked to the more up-to-date source for the same TC39 team saying it's Stage 4, finished, a standard. I also invite you to read the most up-to-date source for the ECMAScript standard – https://tc39.es/ecma262/ – which references top-level `await` as well. In the introduction it also links which standards it includes: https://github.com/tc39/proposals/blob/HEAD/finished-proposals.md and there you will also find top-level `await`.

I was hoping you would link to that page. So by your own link, it says "Expected publication Year 2022". The current year is 2021, so it would appear that this feature has not been published yet.

> I am only responding to you in the hopes that it inspires less reactionary comments based on hunches, and that you research your statements in the hopes that we can all agree much sooner on what is the actual state of things.

I hope you can understand that the current year is 2021, and also that just because something works in the current Chrome console, doesnt mean its standardized.

> I explicitly stated to run it in a browser console. I said "Chrome" though "Firefox" or "Safari 15" are valid substitutes. I am sure as a Node.js developer choosing to run browser code in Node.js you are aware of the API differences and in choosing to do so (even if I never asked anyone to run this in Node.js), you would be able to substitute the code for a suitable asynchronous API in Node.js. So I don't understand why you're telling me not to post it.

Node is a valid platform for JavaScript, so I dont see anything wrong with trying your original code as-is. Not to mention, that I tried it both as module and non-module.

**Comment by blixt** [comment]
Okay, maybe I'm wrong in thinking that while the standard is snapshotted yearly it's a running standard and that things that run the full process into the specification will never get taken out of the specification without another proposal process. Please let me know if that's the case because then I've been misinterpreting how web standards work.

I also concede that I could have written an example that works in any platform and not just browser platforms.

I think that's it for me in this issue, I think we already added too much noise for Taco, that isn't really productive with regards to the original issue or the next action items.

**Comment by 89z** [comment]
> I think that's it for me in this issue, I think we already added too much noise for Taco, that isn't really productive with regards to the original issue or the next action items.

My main beef, is that if you just look at the original comment only, personally I read it as something very matter of fact, like arrays arent supported or something.

When the reality is, depending on your definition, youre describing something that hasnt been standardized yet. People can have their own opinions, but I personally I dont think this package should be supporting stuff that hasnt been standardized.

So instead of realizing that fact and backing off, you dug in deeper trying to argue what the defintion of standardized is, when that doesnt really matter. What matters to me, is that this feature is new enough that I would say its acceptable not the be supported here. Ultimately that not my decision to make, but I can make my position known. I was bothered by how what is by any defintion a new feature, wasnt presented as such.

**Comment by blixt** [comment]
Fair enough, I apologize for approaching it in such a headfast way. It is a feature I've tracked for a long time and now that it's in the spec and all major JS platforms I got a bit passionate about it. I'll take care to report issues with a little more nuance since me arguing about what is a spec isn't really productive, while getting to an agreement to support the feature is.

**Comment by tdewolff** [comment]
The proposal is already in ECMA2022 (the latest spec document at https://tc39.es/ecma262) which this library follows. So I've implemented the proposal, please let me know if you bump into issues!
